# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~

    # your filter sets are defined here
    filter_sets:
        cache: ~

        # the name of the "filter set"
        course_thumb:

            quality: 75

            # list of transformations to apply (the "filters")
            filters:
                thumbnail: { size: [ 800 , 680 ], mode: outbound }

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                downscale:

                    # input 3960x2560px -> output 1980x1280px
                    max: [ 1350, 1080 ]

        # the name of the "filter set"
        course_index:

            quality: 75

            # list of transformations to apply (the "filters")
            filters:
                thumbnail: { size: [ 960 , 540 ], mode: outbound }

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                downscale:

                    # input 3960x2560px -> output 1980x1280px
                    max: [ 1920, 1080 ]
