# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                location: '%kernel.project_dir%/var/storage'
        default_adapter:
            local:
                location: '%kernel.cache_dir%/flysystem'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
            alias: League\Flysystem\Filesystem
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem