vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
        lession_docs:
            uri_prefix: /uploads/lessons/docs
            upload_destination: '%kernel.project_dir%/var/storage/lessons/docs'

        course_image:
            uri_prefix: /uploads/course/image
            upload_destination: '%kernel.project_dir%/public/uploads/course/image'

        course_user_images:
            uri_prefix: /uploads/course/user/image
            upload_destination: '%kernel.project_dir%/public/uploads/course/user/image'

